# Generated by Django 4.2.5 on 2023-09-25 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_rename_unt_price_product_unit_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="last_updated",
            new_name="last_update",
        ),
    ]
