# Generated by Django 4.2.5 on 2023-09-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_product_inventory_alter_product_promotions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="promotions",
            field=models.ManyToManyField(blank=True, to="store.promotion"),
        ),
    ]
