# Generated by Django 4.2.5 on 2023-09-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_review_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
