# Generated by Django 4.2.5 on 2023-10-04 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_alter_review_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
