# Generated by Django 4.2.5 on 2023-10-04 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_cart_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="id",
        ),
        migrations.AlterField(
            model_name="cart",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
