# Generated by Django 4.2.5 on 2023-10-04 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_remove_cart_id_alter_cart_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="uuid",
            new_name="id",
        ),
    ]
